import './globals.css'
import type { Metadata } from 'next'
import { cookies } from "next/headers"
import { dir } from 'i18next'

import { languages } from "@/i18n/settings"
import { ClientCookiesProvider } from '@/components/providers/cookies-provider'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'
import { AuthProvider } from '@/components/providers/auth-provider'
import { nextFont } from '@/i18n'

export let metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string, }
}) {

  return (
    <html lang={params.lang} dir={dir(params.lang)}>
      <body className={nextFont(params.lang)?.className}>
        <AuthProvider>
          <ClientCookiesProvider value={cookies().getAll()}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <ModalProvider>
                {children}
              </ModalProvider>
            </ThemeProvider>
          </ClientCookiesProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
