import './globals.css'
import type { Metadata } from 'next'
import { cookies } from "next/headers"

import { languages } from "@/i18n/settings"
// import { languages } from '@/config/i18n.config'
import { ClientCookiesProvider } from '@/components/providers/cookies-provider'
import { ThemeProvider } from '@/components/providers/theme-provider'
import ModalProvider from '@/components/providers/modal-provider'
import AuthProvider from '@/components/providers/auth-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string, }
}) {


  return (
    <html lang={params.lang} >
      <body >
        <AuthProvider>
          <ClientCookiesProvider value={cookies().getAll()}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <ModalProvider>
                {children}
              </ModalProvider>
            </ThemeProvider>
          </ClientCookiesProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
